language: node_js
node_js:
  - '12'
dist: trusty
cache:
  directories:o
    - node_modules
script:
  - npm run test
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: project-eventos-choclo
  